name: stock_forecast
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - ta
  - yfinance
  - pandas-datareader
  - pip:
      - xgboost
      - lightgbm
      - tensorflow
      - shap
      - streamlit
      - fastapi
      - uvicorn